# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Eric Born
title: Data Scientist
email:  eric.born85@gmail.com
website: ericborn.github.io

# Social links
#twitter_username: facespics
github_username:  ericborn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: borneric
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Eric and I'm a data scientist. I enjoy data exploration, presentation and creating cool tools that help businesses run more efficiently through data driven decision making. 

  I am most skilled in: <mark>Python</mark> <mark>R</mark> <mark>Machine Learning</mark> and <mark>SQL</mark>  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and analytics some of my other hobbies are:
   - Gaming
   - DJing
   - Craft Beer

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
